//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("r2rml.net Core Library")]
[assembly: AssemblyDescription("Library for creating and loading of R2RML mappings")]
[assembly: AssemblyCompany("http://r2rml.net/")]
[assembly: AssemblyProduct("TCode.r2rml4net")]
[assembly: AssemblyCopyright("Copyright © Tomasz Pluskiewicz 2012")]
[assembly: ComVisible(false)]
[assembly: Guid("75adf600-efa6-4088-aac7-af2c7e4d74c4")]
[assembly: AssemblyVersion("0.3.0.4653")]
[assembly: AssemblyFileVersion("0.3.0.0")]
[assembly: InternalsVisibleTo("TCode.r2rml4net.Mapping.Tests")]


[assembly: InternalsVisibleTo("TCode.r2rml4net.Tests")]
