//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("r2rml.net Mapping Library")]
[assembly: AssemblyDescription("Library for creating and loading of R2RML mappings")]
[assembly: AssemblyCompany("http://r2rml.net/")]
[assembly: AssemblyProduct("TCode.r2rml4net.Mapping")]
[assembly: AssemblyCopyright("Copyright © Tomasz Pluskiewicz 2012")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("0.2.0.4653")]
[assembly: AssemblyFileVersion("0.2.0.0")]
[assembly: InternalsVisibleTo("TCode.r2rml4net.Mapping.Tests")]


[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2,PublicKey=0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7")]
